### ISSUE TITLE
Bug: Repo with no languages throws error in the Language widget

### ISSUE THREAD

**Issue by adamdmharvey** [RoadieHQ/backstage-plugin-github-insights#10]
## Issue

I used an empty repo with just a README and a `catalog-info.yaml` as a test, and happened to cause the Languages Widget errors out:

![image](https://user-images.githubusercontent.com/33203301/97382434-c80c9080-18a1-11eb-8bc6-bff802b8b63a.png)

## Visual verification

Sure enough, when I visually look at the repo, it lacks a languages bar visible:

![image](https://user-images.githubusercontent.com/33203301/97383163-52092900-18a3-11eb-9a1b-238f9d30904e.png)

Versus another small repo with some real code stored into it:

![image](https://user-images.githubusercontent.com/33203301/97383190-65b48f80-18a3-11eb-8bac-49813c88f458.png)

## API Verification

My new repo which is causing the error:

```sh
$ curl --user "myuser:mypat" https://github.company.com/api/v3/repos/myuser/brand-new-repo/languages
{

}
```

And a "good" one with code:

```sh
# expected
$ curl --user "myuser:mypat" https://github.company.com/api/v3/repos/myuser/repo-with-code/languages
{
  "Batchfile": 2313,
  "Shell": 380
}
```

## Notes

To be fair this is likely an edge case, but at least means there may need to be an extra error check (and a test?) if some aspect of the GitHub API get repo languages call errors out:
https://docs.github.com/en/free-pro-team@latest/rest/reference/repos#list-repository-languages

## To reproduce

1. Create a new repo
2. Create a very simple README.md
3. Add a catalog-info.yaml for the relevant repo
4. Register existing component with this catalog-info.yaml
5. View GitHub Insights plugin
6. See broken Languages widget

**Comment by dtuite** [comment]
@lewtakm is this fixed and released (and merged upstream in Backstage) yet?

**Comment by adamdmharvey** [comment]
Don't see this merged upstream into Backstage yet:
https://github.com/backstage/backstage/blob/master/packages/app/package.json#L37

I think it was attempted to be fixed in #11 ?

But I updated my local copy, and I can't seem to get it to work. I believe I've done it correctly, tried a few times, but did a `yarn cache clean`, modified my `packages/app/package.json` , did a `yarn upgrade @roadiehq/backstage-plugin-github-insights@0.2.11` from the root of the cloned `backage/backstage` repo (I'm just testing), and I validate this:

```
~/github/backstage(master)*$ grep -r "github-insights" * | grep "0\.2\."
packages/app/package.json:    "@roadiehq/backstage-plugin-github-insights": "0.2.11",
yarn.lock:"@roadiehq/backstage-plugin-github-insights@0.2.11":
yarn.lock:  resolved "https://registry.npmjs.org/@roadiehq/backstage-plugin-github-insights/-/backstage-plugin-github-insights-0.2.11.tgz#2d915c144faf94130a6ca16debd62cf8d2d4692e"
```

And I then did:

```
yarn cache clear
yarn install
yarn tsc
yarn build
```

...but I still get the same error...

**Comment by lewtakm** [comment]
I tested it with 0.2.11 version and it works correctly. I think yarn.lock file block plugin update. I will open PR today to the backstage upstream with update.

**Comment by lewtakm** [comment]
New version of the plugin is now in Backstage sample app. Try using ```yarn install``` now. It should works.

**Comment by adamdmharvey** [comment]
Tried everything clean today and it works beautifully on 0.2.12 - great! Thanks!!!
