### ISSUE TITLE
README suggests to implement deprecated composability

### ISSUE THREAD

**Issue by adamdmharvey** [RoadieHQ/backstage-plugin-github-insights#112]
## Expected Behavior

README reflects the current steps to install the plugin.

## Current Behavior

Following the README, implements a deprecated router:

https://github.com/RoadieHQ/backstage-plugin-github-insights#plugin-setup

VS Code showing me it's deprecated:
![image](https://user-images.githubusercontent.com/33203301/108460368-86379980-7246-11eb-8518-96109b00a27b.png)
![image](https://user-images.githubusercontent.com/33203301/108460382-8fc10180-7246-11eb-8e83-cafaab6c503c.png)

## Possible Solution

Updates to the README.

## Steps to Reproduce

1. Step 1
2. Step 2
3. ...

## Context

I just took a newly created app and followed the instructions, realizing out of the box the router as defined was marked as `@deprecated`.  So I know the composability work was changed recently, and sounds like this plugin was also, so the README may just need some small tweaks.

## Your Environment

- Plugin Version (version of this software e.g. v0.4.3):
- Backstage version (e.g. 0.1.1-alpha23):
- NodeJS Version (e.g. v12):
- Operating System and Version (e.g. Ubuntu 14.04):
- Browser Information (e.g. chrome 85):

**Comment by Irma12** [comment]
@adamdmharvey Thank you for raising this with the team. We appreciate your feedback, and have updated README file. 🎉
