### ISSUE TITLE
Link in Read Me Card is Broken

### ISSUE THREAD

**Issue by sarahpmedeiros** [RoadieHQ/backstage-plugin-github-insights#113]
The Github Insights README says: 
>By default the plugin will use the annotation github.com/project-slug and get the root README.md

but then hardcodes README.MD for the URL path in the Read me card. Causing the Read me link to go to a Github 404 page.

## Expected Behavior 
Clicking the "Read me ->" without the annotation github.com/project-readme-path, gets the root README.md from the repository.

## Current Behavior
Clicking the "Read me ->" without the annotation github.com/project-slug, gets the root README.MD from the repository. This 404s since the file in our repo is README.md  and not README.MD.

## Possible Solution
Update https://github.com/RoadieHQ/backstage-plugin-github-insights/blob/main/src/components/Widgets/ReadMeCard/ReadMeCard.tsx#L69 to be `README.md`

Or

Use the result from hitting Githubs API for /readme to get the repo's readme URL.

## Steps to Reproduce
Unfortunately I can't link to our instance. 

1. In Backstage catalog, go to a component that has the Github insights plugin and whose repo's readme file name is `README.md`
2. In the `Read me` Card, click "Read me ->".

## Context
The read me link is broken for our repos because we name our Github readme's as `README.md`

## Your Environment
We use Github Enterprise

- Plugin Version (version of this software e.g. v0.4.3): ^0.2.7
- Backstage version (e.g. 0.1.1-alpha23): release-2021-01-14
- NodeJS Version (e.g. v12): v14
- Operating System and Version (e.g. Ubuntu 14.04): macOS Mojave
- Browser Information (e.g. chrome 85): Chrome 88

**Comment by dtuite** [comment]
Thanks @sarahpmedeiros. We will get someone to look at this soon.

**Comment by sarahpmedeiros** [comment]
Hi @dtuite, thank you for your quick response. Do you know how long we should wait to expect a resolution?

**Comment by dtuite** [comment]
@sarahpmedeiros I don't, sorry.

**Comment by padraigobrien** [comment]
Hi @sarahpmedeiros I am looking at this now, i will give you an update soon

**Comment by padraigobrien** [comment]
Hi @sarahpmedeiros , A PR was submitted for this today

**Comment by padraigobrien** [comment]
Hi @sarahpmedeiros , we made the change and it has been deployed. i will close this issue now.
