### ISSUE TITLE
EntityGithubInsightsContent consumes entity via props

### ISSUE THREAD

**Issue by Rugvip** [RoadieHQ/backstage-plugin-github-insights#125]
To fully migrate to the composability API the entity page components need to consume the entity via context rather than props, i.e. via `useEntity`. The typical pattern is to make the `entity` prop optional and ignore it, allowing existing code to keep passing it while still supporting the new method.

**Comment by Xantier** [comment]
Addressed in https://github.com/RoadieHQ/backstage-plugin-github-insights/pull/164
