### ISSUE TITLE
GitHub Enterprise Contributor popups don't work: Fetching Failed on avatar icons

### ISSUE THREAD

**Issue by adamdmharvey** [RoadieHQ/backstage-plugin-github-insights#14]
When I view the Insights Panel, I successfully have the contributors panel, languages, and so on.  In my Backstage config, I use both GitHub Enterprise OAuth for authentication, but also have a GHE Token defined, as evidenced by the fact that the plugin can pull this data in the first place.

However, when I hover over the image icons for my contributors, I get a red popup that says:

> (!) Fetching Failed!

![image](https://user-images.githubusercontent.com/33203301/98970674-34ac9f80-24de-11eb-857a-32bcc6feb1b7.png)

Using the devtools in Chrome, I can see what it's doing I believe is actually _directly_ hitting my GHE instance API but from the web browser?  However, it's not my web browser that knows the API Auth Token to use, and so my instance is returning me a 401 unauthorized.  I wonder if this needs to be routed through the Backstage proxy in some fashion or another, and the link in this widget to be re-written for that purpose?

Any other suggestions or ideas?

**Comment by lewtakm** [comment]
Hello,
thanks for a report and pointing out this issue. Requests for contributors avatars was not authorized using GitHub token. It was working on "standard" repositories. I opened PR to fix this issue. As soon as it will be reviewed I will publish new package on NPM and open PR to Backstage upstream to update plugin version.

**Comment by dtuite** [comment]
This is the PR which merges this upstream. https://github.com/backstage/backstage/pull/3315
