### ISSUE TITLE
Relative links to Markdown files in Readme card is broken

### ISSUE THREAD

**Issue by kuangp** [RoadieHQ/backstage-plugin-github-insights#165]
## Expected Behavior
Relative markdown links in the README.md to other .md files in the repo should work.

## Current Behavior

Links are routing to the raw view in Github with the file extension stripped and replaced with a `/` causing the broken links 

## Steps to Reproduce

1. Create a relative link to another markdown file in the repo in the README.md eg. `./packages/foo/CHANGELOG.md`
2. Click on the link in the README card of the plugin
3. Link routes to `https://github.com/my-org/mr-proj/raw/master/packages/foo/CHANGELOG/` instead of `https://github.com/my-org/mr-proj/raw/master/packages/foo/CHANGELOG.md`

## Context

I believe this bug was introduced in https://github.com/RoadieHQ/backstage-plugin-github-insights/commit/1018fd2c1d5d8e65f454a4167c72891a51cc6f0f and is due to this regex replacement:
https://github.com/RoadieHQ/backstage-plugin-github-insights/blob/c97cdbae5120cf07d0ae4cc13cf23dd3b60ede57/src/components/Widgets/ReadMeCard/ReadMeCard.tsx#L117-L120

I'm not sure its correct to assume that relative `.md` links will refer to an existing TechDocs page. Maybe this should be toggled via a plugin config?

## Your Environment

- Plugin Version (version of this software e.g. v0.4.3): 1.0.0

**Comment by Irma12** [comment]
@kuangp Thank you for reporting this. There are some overall challenges that need to be targeted for the markdown documents which are not inside docs folder or properly configured for usage within TechDocs, so for now we have decided to go with the solution which will lead you to location of the document on your repository. However, if you use absolute path inside your README, you will be lead to markdown document in TechDocs page. Hope this helps :)
