### ISSUE TITLE
Broken readme link

### ISSUE THREAD

**Issue by O5ten** [RoadieHQ/backstage-plugin-github-insights#17]
When i click the readme-link that directs me to our resident GitHub Enterprise repo readme i end up at a malformed URL without the colon **(:)** of the protocol https//ghe.some.company.com. 

If you click here: 
![image](https://user-images.githubusercontent.com/3242379/99361904-16b2b680-28b3-11eb-8fd3-8e29932db195.png)

Link showing in the bottom of the browser before click:
![image](https://user-images.githubusercontent.com/3242379/99362018-3649df00-28b3-11eb-8d81-34349966b009.png)

Link showing in the omnibar after following the link:
![image](https://user-images.githubusercontent.com/3242379/99362150-685b4100-28b3-11eb-8bc6-203a8d8eeade.png)

## Expected Behavior

I expect to end up at my example-docker-service readme. 

## Current Behavior

I end up at a malformed URL

## Possible Solution

Figure out where the colon is removed in the backstage redirect link. 

## Steps to Reproduce

1. Open a component with a github readme
2. follow the readme link

## Context

Not a particularly important feature to me so i guess it doesn't bug too many. But still, links should work! :) 
The GHE is protected with SAML2 authentication if that may matter. 
Originally created the issue in the backstage project here: https://github.com/backstage/backstage/issues/3312

## Your Environment

- NodeJS Version (v12):  v12.19.0
- Operating System and Version (e.g. Ubuntu 14.04): RHEL7 for host os, application running in docker container packaged by vanilla Dockerfiles from the backstage project. 
- Browser Information: Chrome, Version 86.0.4240.193 (Official Build) (64-bit)

**Comment by lewtakm** [comment]
Hello,
can you tell me in what format you setup your **host** variable in app-config.yaml file?

**Comment by O5ten** [comment]
```
integrations:
  github:
    - host: https://ghe.***********.com
      apiBaseUrl: https://ghe.**********.com/api/v3
      token:
        $env: GITHUB_TOKEN
```

**Comment by lewtakm** [comment]
@O5ten remove **https://** from host variable following the example: 

![Code_00sw1rxFzw](https://user-images.githubusercontent.com/36006588/99379049-71a2d880-28c8-11eb-984d-f0c607ad94d2.png)

**Comment by O5ten** [comment]
Works much better now! The problem was on my end for having ignored the example docs. Perhaps it would make sense to guard for it in the plugin since i doubt i'll be the last user encountering this problem.

**Comment by lewtakm** [comment]
I am glad to hear that.
I will add some protocol trim to URL in order to prevent such problem in the future. Thanks for suggestion.
