### ISSUE TITLE
Unable to fetch avatars

### ISSUE THREAD

**Issue by O5ten** [RoadieHQ/backstage-plugin-github-insights#18]
Hello! 

This might be more of a question than an issue, but when i open my personal settings page i am met with an anonymous icon, despite being signed into GHE. Is this something i need to configure on my GHE instance or is this something we can resolve from the plugins side? 

```
Cross-Origin Read Blocking (CORB) blocked cross-origin response https://ghe.*********.com/login?return_to=https%3A%2F%2Fghe.************.com%2Favatars%2Fu%2F399%3F with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.
```

Browser:  **Chrome**, version 86.0.4240.193 (Official Build) (64-bit)
GHE Auth: Secured with SAML2
Backstage Auth: OAuth2 through GHE
Backstage is running HTTP and not HTTPS. 
Plugin version: **0.2.12**

**Comment by lewtakm** [comment]
Hello,
if I understood you correctly you are referring to /settings page in your Backstage app. Since this is not related to the plugin itself you should report this problem to Backstage team here:  https://github.com/backstage/backstage/issues

**Comment by andrewthauer** [comment]
I think this is has to do with CSP policy when backstage is running using `https`. I've noticed the same problem in our deployed version, but it's not an issue running locally. I suspect something like this might need to be added to the `app-config.yaml` file but haven't attempted to fix it yet.

```yaml
backend:
  csp:
    img-src: ["'self'", "data:", "https://ghe..."]
```

**Comment by O5ten** [comment]
@andrewthauer that didn't help unfortunately. And my backstage setup is not running https yet either.

**Comment by lewtakm** [comment]
@andrewthauer problem with contributors avatar should be resolved by this pr: https://github.com/RoadieHQ/backstage-plugin-github-insights/pull/16
I open a PR to Backstage upstream to update the plugin version so yarn install would pick up the changes. Its waiting for a merge right now 👍

**Comment by O5ten** [comment]
Fantastic! :)

**Comment by dtuite** [comment]
@O5ten as mentioned, this requires a fix in upstream backstage/backstage and doesn't appear to be related to this plugin. I believe Andrew is hinting at the fix. I'd recommend opening an issue on the Backstage repo.
