### ISSUE TITLE
Language color button isn't visible for HCL code

### ISSUE THREAD

**Issue by adamdmharvey** [RoadieHQ/backstage-plugin-github-insights#47]
## Expected Behavior

* A colored circle appears next to each identified language in the Language widget.
* The associated color is represented in the stacked horizontal bar chart representing it's percentage.

## Current Behavior

One of my languages _seems_ to have no color circle, or it's being flipped somehow based on the theme.

Here's what's actually in my real GitHub repo:

![image](https://user-images.githubusercontent.com/33203301/103013056-86e3d600-450a-11eb-9401-92f2f99af778.png)

And the screen shot of the widget in both light and dark theme. In this screen shot, the HCL code (i.e., Terraform), seems like it has no circle, and it's also missing from the horizontal stacked bar chart:

![image](https://user-images.githubusercontent.com/33203301/103013109-9a8f3c80-450a-11eb-8709-f5114c612cb8.png)

![image](https://user-images.githubusercontent.com/33203301/103013090-919e6b00-450a-11eb-9ae5-c0ce545cbc44.png)

Here's another repo which has the same issue, ALSO for HCL. Not sure if it's HCL which is the issue, or the fact that it's the third one, or not?

![image](https://user-images.githubusercontent.com/33203301/103013250-cc080800-450a-11eb-92b7-3d2ab2d0107b.png)

## Steps to Reproduce

1. Set a github repo annotation in a catalog-info.yaml file
2. Load it into Backstage
3. View Language Widget

## Your Environment

- Plugin Version (version of this software e.g. v0.4.3): 0.2.16
- Backstage version (e.g. 0.1.1-alpha23): 0.4.2
- NodeJS Version (e.g. v12): 12.16.2
- Operating System and Version (e.g. Ubuntu 14.04): Windows 10 19091 WSL2 Ubuntu 18.04
- Browser Information (e.g. chrome 85): Microsoft Edge (Chrome engine)

**Comment by adamdmharvey** [comment]
Interesting. This may literally just be an issue for HCL code. Here's a repo which is FULL of it, and yet the horizontal bar shows only the OTHER code:

![image](https://user-images.githubusercontent.com/33203301/103013858-d4147780-450b-11eb-83ab-3ec780372949.png)

**Comment by adamdmharvey** [comment]
Ah ha, it has something to do with this:

https://github.com/RoadieHQ/backstage-plugin-github-insights/blob/0ec7bfe2dddb2ad71d56577889bdcdc6e1b02028/src/components/Widgets/LanguagesCard/colors.ts#L601-L604

If I hardcode that to bright red, i.e.,

```
 HCL: {
    color: '#ff0000',
    url: 'https://github.com/trending?l=HCL',
  },
```

Then it works:

![image](https://user-images.githubusercontent.com/33203301/103018641-9582bb00-4513-11eb-8edd-360be951d7f4.png)

So maybe it just doesn't like the `inherit` value?

**Comment by Irma12** [comment]
@adamdmharvey Thank you for reporting the issue. We have worked on the fix and it should be displayed now :)
