### ISSUE TITLE
Add GitHub "Release Title" to Releases Card

### ISSUE THREAD

**Issue by adamdmharvey** [RoadieHQ/backstage-plugin-github-insights#63]
## Feature Suggestion

The current Releases Card displays a list of versioned releases.  It would be great to augment this list if the repo in question has defined release titles. This is the metadata above and beyond just the tag name,

For example, this sample card:

![image](https://user-images.githubusercontent.com/33203301/105089619-5c366000-5a6b-11eb-81e4-130319e3afb4.png)

Could be really useful if this additional info was added to it:

![image](https://user-images.githubusercontent.com/33203301/105089741-8425c380-5a6b-11eb-9a8b-fa2f107d58ae.png)

## Possible Implementation

Something like:

Release Title (v3.3.3)

With the entire thing linked to get to the release, as it is now.  In addition, adding contextual data like if it's a pre-release, etc, might be super valuable! (the info that can be released to end users; not talking about DRAFT which is visible only to repo admins)

## Context

Helps elevate any contexual release info a product team may be attempting to display for their releases.

**Comment by Irma12** [comment]
@adamdmharvey Thank you for great suggestion, we have implemented the improvements and everything is up and running in v1.1.0. You can check it out :)
