### ISSUE TITLE
catalog component readme doesn't include embedded images

### ISSUE THREAD

**Issue by n2ygk** [RoadieHQ/backstage-plugin-github-insights#81]
[Originally posted as backstage/backstage/issues/4345]

This is a pretty minor nit, but the catalog/default/component/_component-name_ pulls in the README.md but not
any referenced images that are pulled in, e.g. via `![alt-text](docs/media/CCbyncsa4.0.png "CC BY-NC-SA 4.0")`

## Expected Behavior

The "mini" README should render completely

## Current Behavior

Image references are rendered as broken images:
![image](https://user-images.githubusercontent.com/4356471/106511134-d15b5980-649d-11eb-8160-8eda4d682b63.png)

## Steps to Reproduce

1. Add this component: https://github.com/columbia-it/django-jsonapi-training/blob/master/catalog-info-github.yaml
2. Go to http://localhost:3000/catalog/default/component/django-jsonapi-training

## Your Environment

- Plugin Version (version of this software e.g. v0.4.3): 0.2.16
- Backstage version (e.g. 0.1.1-alpha23): @backstage/catalog-client: 0.3.5
- NodeJS Version (e.g. v12): v12.20.1
- Operating System and Version (e.g. Ubuntu 14.04): MacOS Catalina 10.15.7 (19H114)
- Browser Information (e.g. chrome 85): Chrome 88

**Comment by jessebye** [comment]
@n2ygk we got around this by updating our CSP like so:

```
backend:
  csp:
    img-src: [ "'self'", 'data:', 'https:' ]
```

**Comment by n2ygk** [comment]
>   csp:
>     img-src: [ "'self'", 'data:', 'https:' ]

hmm, not working for me... I'll dig further.

**Comment by martina-if** [comment]
possibly related to #165

**Comment by Irma12** [comment]
@n2ygk Thank you for reporting the issue, we have worked on the fix, please check it out in v1.1.3 🎉

**Comment by n2ygk** [comment]
@Irma12 I updated to 1.1.3 in packages.json but it still doesn't appear to work. Is there something else I should try?
```diff
diff --git a/packages/app/package.json b/packages/app/package.json
index 6acba6f4c..8344ec387 100644
--- a/packages/app/package.json
+++ b/packages/app/package.json
@@ -42,7 +42,7 @@
     "@material-ui/icons": "^4.9.1",
     "@octokit/rest": "^18.5.3",
     "@roadiehq/backstage-plugin-buildkite": "^1.0.0",
-    "@roadiehq/backstage-plugin-github-insights": "^1.0.0",
+    "@roadiehq/backstage-plugin-github-insights": "^1.1.3",
     "@roadiehq/backstage-plugin-github-pull-requests": "^1.0.0",
     "@roadiehq/backstage-plugin-travis-ci": "^1.0.0",
     "history": "^5.0.0",
```

**Comment by Irma12** [comment]
@n2ygk Thanks to your engagement we have found that there was an issue with rendering images with title attribute. However, we have worked on the fix and it should be working now in version **v1.1.10**. Once again, thank you for verifying this and reaching out to us, hope you won't be having issues anymore.

**Comment by n2ygk** [comment]
@Irma12 WooHoo! Thanks!
![image](https://user-images.githubusercontent.com/4356471/118666700-6110e380-b7c1-11eb-83b3-ee09a629c7bc.png)

Will you be bumping the version in Backstage [packages/app/package.json]?(https://github.com/backstage/backstage/blob/99dddfb61001ee823e717047fc3e9e9954a86b04/packages/app/package.json#L45)

**Comment by Irma12** [comment]
Awesome @n2ygk 🎉  I am glad it works now. Yes, we are working on that at the moment so hopefully very soon it will be updated there also :)
